import React from 'react';
import { MaterialIcons } from '@expo/vector-icons';
import { colors } from '../theme/theme';

type IconProps = {
  name: string;
  size?: number;
  color?: string;
};

const materialMap: Record<string, keyof typeof MaterialIcons.glyphMap> = {
  home: 'home',
  plus: 'add',
  bookmark: 'bookmark-border',
  user: 'person-outline',
  itinerary: 'map',
  information: 'info-outline',
  profile: 'person-outline',
  search: 'search',
  bell: 'notifications-none',
  calendar: 'event',
  location: 'place',
  restaurant: 'restaurant',
  flight: 'flight',
  hotel: 'hotel',
  back: 'arrow-back',
  chevronLeft: 'chevron-left',
  chevronRight: 'chevron-right',
  chevronDown: 'expand-more',
  chevronUp: 'expand-less',
  close: 'close',
  delete: 'delete-outline',
  edit: 'edit',
  theme: 'brightness-6',
  demo: 'play-circle-outline',
  logout: 'logout',
  google: 'g-mobiledata',
  mic: 'mic-none',
  time: 'access-time',
  map: 'map',
  save: 'bookmark',
  check: 'check',
  image: 'image',
  camera: 'camera',
  upload: 'cloud-upload',
  link: 'link',
  currency: 'attach-money',
  checklist: 'check-circle',
  document: 'description',
  compass: 'explore',
  globe: 'public',
  heart: 'favorite-border',
  heartFilled: 'favorite',
  swap: 'swap-horiz',
  refresh: 'refresh',
  trash: 'delete',
  lock: 'lock',
  plane: 'flight',
  logo: 'public',
  person: 'person',
  users: 'group',
  star: 'star',
  crown: 'workspace-premium',
  share: 'share',
  filter: 'filter-list',
  sort: 'sort',
  settings: 'settings',
  notification: 'notifications',
  message: 'message',
  send: 'send',
  photo: 'photo',
  video: 'videocam',
  file: 'insert-drive-file',
  download: 'file-download',
  eye: 'visibility',
  eyeOff: 'visibility-off',
  warning: 'warning',
  success: 'check-circle',
  error: 'error',
  info: 'info',
  clock: 'access-time',
  tag: 'local-offer',
  category: 'category',
  flag: 'flag',
  favorite: 'favorite',
  like: 'thumb-up',
  dislike: 'thumb-down',
  comment: 'comment',
  reply: 'reply',
  forward: 'forward',
  attachment: 'attachment',
  emoji: 'emoji-emotions',
  gif: 'gif',
  navigation: 'navigation',
  directions: 'directions',
  nearby: 'near-me',
  explore: 'explore',
  travel: 'card-travel',
  ticket: 'confirmation-number',
  boarding: 'flight-takeoff',
  arrival: 'flight-land',
  transit: 'directions-transit',
  walk: 'directions-walk',
  car: 'directions-car',
  bike: 'directions-bike',
  bus: 'directions-bus',
  train: 'directions-train',
  cafe: 'local-cafe',
  bar: 'local-bar',
  shop: 'shopping-bag',
  gas: 'local-gas-station',
  hospital: 'local-hospital',
  pharmacy: 'local-pharmacy',
  parking: 'local-parking',
  print: 'local-printshop',
  shipping: 'local-shipping',
  laundry: 'local-laundry-service',
  grocery: 'local-grocery-store',
  store: 'store',
  fastfood: 'fastfood',
  arrowUp: 'arrow-upward',
  chat: 'chat-bubble-outline',
};

export const Icon: React.FC<IconProps> = ({ name, size = 22, color = colors.primary }) => {
  const iconName = materialMap[name];
  if (!iconName) {
    console.warn(`Icon "${name}" not found`);
    return <MaterialIcons name="help-outline" size={size} color={color} />;
  }
  return <MaterialIcons name={iconName} size={size} color={color} />;
};

export default Icon;